/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/servicios': typeof ServiciosRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/servicios': typeof ServiciosRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/servicios': typeof ServiciosRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/servicios'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citas'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/servicios'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/citas'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/servicios'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitasRoute: typeof CitasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  ServiciosRoute: typeof ServiciosRoute
  PacientesIdRoute: typeof PacientesIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitasRoute: CitasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  ServiciosRoute: ServiciosRoute,
  PacientesIdRoute: PacientesIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
